# Generated by Django 5.0.6 on 2024-06-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_user_roles_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_goal',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date_closed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IP', 'In process'), ('WE', 'Waiting for employer'), ('DN', 'Done')], default='WE'),
        ),
    ]
